---

- name: Common HA configuration on all devices
  hosts: f5-test
  connection: local

  vars:
    provider:
      server: "{{ ansible_host }}"
      server_port: "{{ f5_server_port }}"
      user: "{{ f5_username }}"
      password: "{{ f5_password }}"
      validate_certs: "{{ validate_certs }}"

  tasks:
    - include_tasks: validate.yaml

    - name: Add VLANs
      bigip_vlan:
        name: "{{ item.vlan.name }}"
        tag: "{{ item.vlan.tag }}"
        untagged_interfaces: "{{ item.vlan.interfaces }}"
        provider: "{{ provider }}"
      loop: "{{ nets }}"

    - name: Add Self-IPs
      bigip_selfip:
        name: "{{ item.name }}"
        address: "{{ item.address }}"
        netmask: "{{ item.netmask }}"
        vlan: "{{ item.vlan.name }}"
        provider: "{{ provider }}"
        allow_service:
          - all
      loop: "{{ nets }}"

    - name: Configure hostname
      bigip_hostname:
        hostname: "{{ inventory_hostname }}"
        provider: "{{ provider }}"

    - name: Set CMI device parameters
      bigip_device_connectivity:
        config_sync_ip: "{{ config_sync_ip }}"
        mirror_primary_address: "{{ mirror_primary_address }}"
        unicast_failover: "{{ unicast_failover }}"
        provider: "{{ provider }}"

- name: Primary device specific configuration
  hosts: f5-test[0]
  connection: local

  vars:
    provider:
      server: "{{ ansible_host }}"
      server_port: "{{ f5_server_port }}"
      user: "{{ f5_username }}"
      password: "{{ f5_password }}"
      validate_certs: "{{ validate_certs }}"

  tasks:
    - name: Trust peer device
      bigip_device_trust:
        peer_server: "{{ hostvars[item].ansible_host }}"
        peer_hostname: "{{ hostvars[item].inventory_hostname }}"
        peer_user: "{{ f5_username }}"
        peer_password: "{{ f5_password }}"
        provider: "{{ provider }}"
      loop: "{{ groups['f5-test'][1:] }}"

    - name: Add Device Group
      bigip_device_group:
        name: deviceGrp
        auto_sync: yes
        type: sync-failover
        provider: "{{ provider }}"

    - name: Add members to the device group
      bigip_device_group_member:
        device_group: deviceGrp
        name: "{{ item }}"
        provider: "{{ provider }}"
      loop: "{{ groups['f5-test'] }}"

    - name: Perform a config sync
      bigip_configsync_action:
        device_group: deviceGrp
        sync_device_to_group: yes
        provider: "{{ provider }}"
