---

- include: setup.yaml

- name: Create iApp Service
  iworkflow_service:
      service_template: "foo-service-template-1"
      connector: "{{ connector_name1 }}"
      name: "foo-service-1"
      parameters: "{{ lookup('file', 'service_params_correct.json') }}"
      tenant: "{{ tenant_name }}"
      state: "present"
  register: result

- name: Assert Create iApp Service
  assert:
      that:
          - result|changed

#- name: Create iApp Service - Idempotent check
#  iworkflow_service:
#      service_template: "appsvcs_integration_v2.0_001"
#      connector: "{{ connector_name1 }}"
#      name: "foo-service-1"
#      parameters: "{{ lookup('file', 'service_params_correct.json') }}"
#      tenant: "{{ tenant_name }}"
#      state: "present"
#  register: result
#
#- name: Assert Create iApp Service - Idempotent check
#  assert:
#      that:
#          - not result|changed
#
#- name: Remove iApp Service
#  iworkflow_service:
#      name: "foo-service-1"
#      tenant: "{{ tenant_name }}"
#      state: "absent"
#  register: result
#
#- name: Assert Remove iApp Service
#  assert:
#      that:
#          - result|changed
#
#- name: Remove iApp Service
#  iworkflow_service:
#      name: "foo-service-1"
#      tenant: "{{ tenant_name }}"
#      state: "absent"
#  register: result
#
#- name: Assert Remove iApp Service - Idempotent check
#  assert:
#      that:
#          - not result|changed
#
#- include: teardown.yaml
