---

- name: Create a VIP, pool, pool members and nodes
  hosts: f5-test
  connection: local

  vars:
    bigip_license: "XXXXX-XXXXX-XXXXX-XXXXX-XXXXXXX"
    provider:
      password: "{{ f5_password }}"
      server: "{{ ansible_host }}"
      user: "{{ f5_username }}"
      validate_certs: "{{ validate_certs }}"
      server_port: "{{ f5_server_port }}"

  tasks:
    - name: License a BIG-IP
      bigip_license:
        key: "{{ bigip_license }}"
