---

- name: Remove VIP, pool, pool members and nodes
  hosts: all
  connection: local

  vars:
    provider:
      password: admin
      server: 1.1.1.1
      user: admin
      validate_certs: no
      server_port: 443

  tasks:
    - name: Destroy a VIP
      bigip_virtual_server:
        provider: "{{ provider }}"
        name: vip-1
        state: absent
      delegate_to: localhost

    - name: Destroy a pool
      bigip_pool:
        provider: "{{ provider }}"
        name: web
        state: absent
      delegate_to: localhost

    - name: Delete nodes
      bigip_node:
        provider: "{{ provider }}"
        name: "{{ item }}"
        state: absent
      loop:
        - web01
        - web02
      delegate_to: localhost
