---

- name: Configure Basic vlans, ips, virtuals, license
  hosts: v11-2
  environment:
      F5_SERVER: "{{ inventory_hostname }}"
      F5_USER: "admin"
      F5_PASSWORD: "admin"
      F5_VALIDATE_CERTS: "false"
      F5_SERVER_PORT: 443
  connection: local
  vars:
      unit_hostname: "v11-2.wehrman.com"

  tasks:
    - name: Reset to base configuration
      bigip_command:
          commands: load sys config default

    - name: Set the bigip-hostname
      bigip_hostname:
          hostname: "{{ unit_hostname }}"

    - name: Renew license
      bigip_license:
          key: "XXXXX-XXXXX-XXXXX-XXXXX-XXXXXX"
          state: "latest"

    - name: Pause 1 minute to allow the default config to load or some later steps may fail
      pause:
           minutes: 1
    - name: Configure vlan external
      bigip_vlan:
          name: "external"
          tag: "2001"
          untagged_interfaces: 1.1
    - name: Configure vlan internal
      bigip_vlan:
          name: "internal"
          tag: "2002"
          untagged_interfaces: 1.2
    - name: Configure vlan HA
      bigip_vlan:
          name: "HA"
          tag: "2003"
          untagged_interfaces: 1.3
    #create self IP's
    - name: Create external self
      bigip_selfip:
          address: "12.13.14.2"
          name: "external_self"
          netmask: "255.255.255.0"
          vlan: "external"
    - name: Create internal self
      bigip_selfip:
          address: "11.12.13.2"
          name: "internal_self"
          netmask: "255.255.255.0"
          vlan: "internal"

    - name: Mark setup as having been run so it doesn't display that on login
      bigip_command:
          commands: modify sys db setup.run value false

    - name: Configure NTP server
      bigip_command:
          commands:  modify sys ntp servers add { 192.168.11.168 }

    - name: Save this config to file
      bigip_command:
          commands: save sys config

