---

- name: Configure Basic vlans, ips, virtuals, license
  hosts: v11-1
  environment:
      F5_SERVER: "{{ inventory_hostname }}"
      F5_USER: "admin"
      F5_PASSWORD: "admin"
      F5_VALIDATE_CERTS: "false"
      F5_SERVER_PORT: 443
  connection: local
  vars:
      unit_hostname: "v11-1.wehrman.com"
      nodes:
        - name: 11.12.13.16
          host: 11.12.13.16
        - name: 11.12.13.17
          host: 11.12.13.17
        - name: 11.12.13.18
          host: 11.12.13.18
        - name: 11.12.13.19
          host: 11.12.13.19
  tasks:
    - name: Reset to base configuration
      bigip_config:
          reset: yes

    - name: Set the bigip-hostname
      bigip_hostname:
          hostname: "{{ unit_hostname }}"

    - name: Renew license
      bigip_license:
          key: "XXXXX-XXXXX-XXXXX-XXXXX-XXXXXX"
          state: "latest"

    - name: Pause 1 minute to allow the license to reload or tmsh might not be up
      pause:
           minutes: 1
    - name: Configure vlan external
      bigip_vlan:
          name: "external"
          tag: "2001"
          untagged_interfaces: 1.1
    - name: Configure vlan internal
      bigip_vlan:
          name: "internal"
          tag: "2002"
          untagged_interfaces: 1.2
    - name: Configure vlan HA
      bigip_vlan:
          name: "HA"
          tag: "2003"
          untagged_interfaces: 1.3
    #create self IP's
    - name: Create external self
      bigip_selfip:
          address: "12.13.14.1"
          name: "external_self"
          netmask: "255.255.255.0"
          vlan: "external"
    - name: Create internal self
      bigip_selfip:
          address: "11.12.13.1"
          name: "internal_self"
          netmask: "255.255.255.0"
          vlan: "internal"
#Create Some Nodes - Be careful here - if the first node in the list exists it
# skips the rest.  So if you add to the list it won't run this again if node 1
# exists.
    - name: Add all the nodes
      bigip_node:
          state: "present"
          partition: "Common"
          host: "{{ item.host }}"
          name: "{{ item.name }}"
      with_items: "{{ nodes }}"

#Create Two Pools
    - name: Create pool
      bigip_pool:
          state: "present"
          name: "https_pool"
          partition: "Common"
          lb_method: "round_robin"
          host: "{{ item.host }}"
          port: 80
          monitors:
            - /Common/http
      with_items: "{{ nodes }}"
    - name: Create an http virtual server
      bigip_virtual_server:
          state: "present"
          partition: "Common"
          name: "HTTP_Virtual"
          destination: "10.11.15.23"
          port: "80"
          pool: "https_pool"
          snat: "Automap"
          all_profiles:
            - http
    - name: Create an https virtual server
      bigip_virtual_server:
          state: present
          partition: Common
          name: HTTPS_Virtual
          destination: 10.11.15.23
          port: 443
          pool: https_pool
          snat: Automap
          all_profiles:
            - http
            - clientssl

    - name: Mark setup as having been run so it doesn't display that on login
      bigip_command:
          commands: modify sys db setup.run value false

    - name: Configure NTP server
      bigip_command:
          commands:  modify sys ntp servers add { 192.168.11.168 }

    - name: Save config to file
      bigip_config:
          save: yes

