---

ansible_host: IP_A0

nets:
  - name: Self-Internal
    address: IP_A1
    netmask: 255.255.255.0
    vlan:
      name: Internal
      tag: 10
      interfaces:
        - 1.1
  - name: Self-External
    address: IP_A2
    netmask: 255.255.255.0
    vlan:
      name: External
      tag: 20
      interfaces:
        - 1.2
  - name: Self-HA
    address: IP_A3
    netmask: 255.255.255.0
    vlan:
      name: HA
      tag: 30
      interfaces:
        - 1.3

config_sync_ip: IP_A3
mirror_primary_address: IP_A3
unicast_failover:
  - address: IP_A3
