---

# Example of using a list of dictionaries to create many LTM nodes
#
# This example puts the variables in two places
#
#    * a `vars:` section at the top of the play
#    * inline with the task
#
# It should be noted that these variables themselves do not need to
# exist in the playbook. In fact, it is recommended that you put these
# and other variables in either the host's inventory file or in the
# group's inventory file; whichever is more proper for your use case.
#
# Warning. This playbook will create lots of nodes on your BIG-IP.
# Want to delete those nodes? Set the `state` of the tasks
# to "absent".
#
# Requirements:
#
#   * Ansible >= 2.3
#

- name: Create pools from ports
  hosts: f5-test
  connection: local

  environment:
      F5_SERVER: "{{ inventory_hostname }}"
      F5_USER: "admin"
      F5_PASSWORD: "admin"
      F5_VALIDATE_CERTS: "false"
      F5_SERVER_PORT: 443

  vars:
      nodes:
          - name: 10.10.10.10
            host: 10.10.10.10
          - name: devfoobarweblog01
            host: 10.10.10.11
          - name: devbazsystem01
            host: 10.10.10.12
          - name: devbazsystem02
            host: 10.10.10.13
          - name: devbazsystem03
            host: 10.10.10.14
          - name: devbazsystem04
            host: 10.10.10.15
          - name: devbazsystem05
            host: 10.10.10.16
          - name: devbazsystem06
            host: 10.10.10.17
          - name: devbazsystem07
            host: 10.10.10.18
          - name: devinside01
            host: 10.10.10.100
          - name: devinside02
            host: 10.10.10.200
          - name: devinside03
            host: 10.10.10.201
          - name: devinside04
            host: 10.10.10.202
          - name: devinside05
            host: 10.10.10.203
          - name: devinside06
            host: 10.10.10.204
          - name: devinside07
            host: 10.10.10.205
          - name: devinside08
            host: 10.10.10.206
          - name: devinside09
            host: 10.10.10.207
          - name: devmarketing01
            host: 10.10.20.101
          - name: devmarketing02
            host: 10.10.20.102
          - name: devmarketing03
            host: 10.10.20.103
          - name: devmarketing04
            host: 10.10.20.104
          - name: devmarketing05
            host: 10.10.20.105
          - name: devmarketing06
            host: 10.10.20.106
          - name: devmarketing07
            host: 10.10.20.107
          - name: devmarketing08
            host: 10.10.20.108
          - name: devmarketing09
            host: 10.10.20.109
          - name: devmarketing10
            host: 10.10.20.110
          - name: devmarketing11
            host: 10.10.20.111
          - name: devmarketing12
            host: 10.10.20.112

          - name: tstfoobarweblog01
            host: 10.20.10.11
          - name: tstbazsystem01
            host: 10.20.10.12
          - name: tstbazsystem02
            host: 10.20.10.13
          - name: tstbazsystem03
            host: 10.20.10.14
          - name: tstbazsystem04
            host: 10.20.10.15
          - name: tstbazsystem05
            host: 10.20.10.16
          - name: tstbazsystem06
            host: 10.20.10.17
          - name: tstbazsystem07
            host: 10.20.10.18
          - name: tstinside01
            host: 10.20.10.100
          - name: tstinside02
            host: 10.20.10.200
          - name: tstinside03
            host: 10.20.10.201
          - name: tstinside04
            host: 10.20.10.202
          - name: tstinside05
            host: 10.20.10.203
          - name: tstinside06
            host: 10.20.10.204
          - name: tstinside07
            host: 10.20.10.205
          - name: tstinside08
            host: 10.20.10.206
          - name: tstinside09
            host: 10.20.10.207
          - name: tstmarketing01
            host: 10.20.20.101
          - name: tstmarketing02
            host: 10.20.20.102
          - name: tstmarketing03
            host: 10.20.20.103
          - name: tstmarketing04
            host: 10.20.20.104
          - name: tstmarketing05
            host: 10.20.20.105
          - name: tstmarketing06
            host: 10.20.20.106
          - name: tstmarketing07
            host: 10.20.20.107
          - name: tstmarketing08
            host: 10.20.20.108
          - name: tstmarketing09
            host: 10.20.20.109
          - name: tstmarketing10
            host: 10.20.20.110
          - name: tstmarketing11
            host: 10.20.20.111
          - name: tstmarketing12
            host: 10.20.20.112

          - name: intfoobarweblog01
            host: 10.30.10.11
          - name: intbazsystem01
            host: 10.30.10.12
          - name: intbazsystem02
            host: 10.30.10.13
          - name: intbazsystem03
            host: 10.30.10.14
          - name: intbazsystem04
            host: 10.30.10.15
          - name: intbazsystem05
            host: 10.30.10.16
          - name: intbazsystem06
            host: 10.30.10.17
          - name: intbazsystem07
            host: 10.30.10.18
          - name: intinside01
            host: 10.30.10.100
          - name: intinside02
            host: 10.30.10.200
          - name: intinside03
            host: 10.30.10.201
          - name: intinside04
            host: 10.30.10.202
          - name: intinside05
            host: 10.30.10.203
          - name: intinside06
            host: 10.30.10.204
          - name: intinside07
            host: 10.30.10.205
          - name: intinside08
            host: 10.30.10.206
          - name: intinside09
            host: 10.30.10.207
          - name: intmarketing01
            host: 10.30.20.101
          - name: intmarketing02
            host: 10.30.20.102
          - name: intmarketing03
            host: 10.30.20.103
          - name: intmarketing04
            host: 10.30.20.104
          - name: intmarketing05
            host: 10.30.20.105
          - name: intmarketing06
            host: 10.30.20.106
          - name: intmarketing07
            host: 10.30.20.107
          - name: intmarketing08
            host: 10.30.20.108
          - name: intmarketing09
            host: 10.30.20.109
          - name: intmarketing10
            host: 10.30.20.110
          - name: intmarketing11
            host: 10.30.20.111
          - name: intmarketing12
            host: 10.30.20.112

          - name: prdfoobarweblog01
            host: 10.40.10.11
          - name: prdbazsystem01
            host: 10.40.10.12
          - name: prdbazsystem02
            host: 10.40.10.13
          - name: prdbazsystem03
            host: 10.40.10.14
          - name: prdbazsystem04
            host: 10.40.10.15
          - name: prdbazsystem05
            host: 10.40.10.16
          - name: prdbazsystem06
            host: 10.40.10.17
          - name: prdbazsystem07
            host: 10.40.10.18
          - name: prdinside01
            host: 10.40.10.100
          - name: prdinside02
            host: 10.40.10.200
          - name: prdinside03
            host: 10.40.10.201
          - name: prdinside04
            host: 10.40.10.202
          - name: prdinside05
            host: 10.40.10.203
          - name: prdinside06
            host: 10.40.10.204
          - name: prdinside07
            host: 10.40.10.205
          - name: prdinside08
            host: 10.40.10.206
          - name: prdinside09
            host: 10.40.10.207
          - name: prdmarketing01
            host: 10.40.20.101
          - name: prdmarketing02
            host: 10.40.20.102
          - name: prdmarketing03
            host: 10.40.20.103
          - name: prdmarketing04
            host: 10.40.20.104
          - name: prdmarketing05
            host: 10.40.20.105
          - name: prdmarketing06
            host: 10.40.20.106
          - name: prdmarketing07
            host: 10.40.20.107
          - name: prdmarketing08
            host: 10.40.20.108
          - name: prdmarketing09
            host: 10.40.20.109
          - name: prdmarketing10
            host: 10.40.20.110
          - name: prdmarketing11
            host: 10.40.20.111
          - name: prdmarketing12
            host: 10.40.20.112

  tasks:
      - name: Lots of nodes - from variable (playbook or inventory)
        bigip_node:
            state: "present"
            name: "{{ item.name }}"
            host: "{{ item.host }}"
        with_items: "{{ nodes }}"
        delegate_to: localhost

      - name: Lots of nodes - inline nodes
        bigip_node:
            state: "present"
            name: "{{ item.name }}"
            host: "{{ item.host }}"
        delegate_to: localhost
        with_items:
            - name: 20.10.10.10
              host: 20.10.10.10
            - name: dev1foobarweblog01
              host: 10.50.10.11
            - name: dev1bazsystem01
              host: 10.50.10.12
            - name: dev1bazsystem02
              host: 10.50.10.13
            - name: dev1bazsystem03
              host: 10.50.10.14
            - name: dev1bazsystem04
              host: 10.50.10.15
            - name: dev1bazsystem05
              host: 10.50.10.16
            - name: dev1bazsystem06
              host: 10.50.10.17
            - name: dev1bazsystem07
              host: 10.50.10.18
            - name: dev1inside01
              host: 10.50.10.100
            - name: dev1inside02
              host: 10.50.10.200
            - name: dev1inside03
              host: 10.50.10.201
            - name: dev1inside04
              host: 10.50.10.202
            - name: dev1inside05
              host: 10.50.10.203
            - name: dev1inside06
              host: 10.50.10.204
            - name: dev1inside07
              host: 10.50.10.205
            - name: dev1inside08
              host: 10.50.10.206
            - name: dev1inside09
              host: 10.50.10.207
            - name: dev1marketing01
              host: 10.50.20.101
            - name: dev1marketing02
              host: 10.50.20.102
            - name: dev1marketing03
              host: 10.50.20.103
            - name: dev1marketing04
              host: 10.50.20.104
            - name: dev1marketing05
              host: 10.50.20.105
            - name: dev1marketing06
              host: 10.50.20.106
            - name: dev1marketing07
              host: 10.50.20.107
            - name: dev1marketing08
              host: 10.50.20.108
            - name: dev1marketing09
              host: 10.50.20.109
            - name: dev1marketing10
              host: 10.50.20.110
            - name: dev1marketing11
              host: 10.50.20.111
            - name: dev1marketing12
              host: 10.50.20.112

            - name: tst1foobarweblog01
              host: 10.20.10.11
            - name: tst1bazsystem01
              host: 10.60.10.12
            - name: tst1bazsystem02
              host: 10.60.10.13
            - name: tst1bazsystem03
              host: 10.60.10.14
            - name: tst1bazsystem04
              host: 10.60.10.15
            - name: tst1bazsystem05
              host: 10.60.10.16
            - name: tst1bazsystem06
              host: 10.60.10.17
            - name: tst1bazsystem07
              host: 10.60.10.18
            - name: tst1inside01
              host: 10.60.10.100
            - name: tst1inside02
              host: 10.60.10.200
            - name: tst1inside03
              host: 10.60.10.201
            - name: tst1inside04
              host: 10.60.10.202
            - name: tst1inside05
              host: 10.60.10.203
            - name: tst1inside06
              host: 10.60.10.204
            - name: tst1inside07
              host: 10.60.10.205
            - name: tst1inside08
              host: 10.60.10.206
            - name: tst1inside09
              host: 10.60.10.207
            - name: tst1marketing01
              host: 10.60.20.101
            - name: tst1marketing02
              host: 10.60.20.102
            - name: tst1marketing03
              host: 10.60.20.103
            - name: tst1marketing04
              host: 10.60.20.104
            - name: tst1marketing05
              host: 10.60.20.105
            - name: tst1marketing06
              host: 10.60.20.106
            - name: tst1marketing07
              host: 10.60.20.107
            - name: tst1marketing08
              host: 10.60.20.108
            - name: tst1marketing09
              host: 10.60.20.109
            - name: tst1marketing10
              host: 10.60.20.110
            - name: tst1marketing11
              host: 10.60.20.111
            - name: tst1marketing12
              host: 10.60.20.112

            - name: int1foobarweblog01
              host: 10.70.10.11
            - name: int1bazsystem01
              host: 10.70.10.12
            - name: int1bazsystem02
              host: 10.70.10.13
            - name: int1bazsystem03
              host: 10.70.10.14
            - name: int1bazsystem04
              host: 10.70.10.15
            - name: int1bazsystem05
              host: 10.70.10.16
            - name: int1bazsystem06
              host: 10.70.10.17
            - name: int1bazsystem07
              host: 10.70.10.18
            - name: int1inside01
              host: 10.70.10.100
            - name: int1inside02
              host: 10.70.10.200
            - name: int1inside03
              host: 10.70.10.201
            - name: int1inside04
              host: 10.70.10.202
            - name: int1inside05
              host: 10.70.10.203
            - name: int1inside06
              host: 10.70.10.204
            - name: int1inside07
              host: 10.70.10.205
            - name: int1inside08
              host: 10.70.10.206
            - name: int1inside09
              host: 10.70.10.207
            - name: int1marketing01
              host: 10.70.20.101
            - name: int1marketing02
              host: 10.70.20.102
            - name: int1marketing03
              host: 10.70.20.103
            - name: int1marketing04
              host: 10.70.20.104
            - name: int1marketing05
              host: 10.70.20.105
            - name: int1marketing06
              host: 10.70.20.106
            - name: int1marketing07
              host: 10.70.20.107
            - name: int1marketing08
              host: 10.70.20.108
            - name: int1marketing09
              host: 10.70.20.109
            - name: int1marketing10
              host: 10.70.20.110
            - name: int1marketing11
              host: 10.70.20.111
            - name: int1marketing12
              host: 10.70.20.112

            - name: prd1foobarweblog01
              host: 10.80.10.11
            - name: prd1bazsystem01
              host: 10.80.10.12
            - name: prd1bazsystem02
              host: 10.80.10.13
            - name: prd1bazsystem03
              host: 10.80.10.14
            - name: prd1bazsystem04
              host: 10.80.10.15
            - name: prd1bazsystem05
              host: 10.80.10.16
            - name: prd1bazsystem06
              host: 10.80.10.17
            - name: prd1bazsystem07
              host: 10.80.10.18
            - name: prd1inside01
              host: 10.80.10.100
            - name: prd1inside02
              host: 10.80.10.200
            - name: prd1inside03
              host: 10.80.10.201
            - name: prd1inside04
              host: 10.80.10.202
            - name: prd1inside05
              host: 10.80.10.203
            - name: prd1inside06
              host: 10.80.10.204
            - name: prd1inside07
              host: 10.80.10.205
            - name: prd1inside08
              host: 10.80.10.206
            - name: prd1inside09
              host: 10.80.10.207
            - name: prd1marketing01
              host: 10.80.20.101
            - name: prd1marketing02
              host: 10.80.20.102
            - name: prd1marketing03
              host: 10.80.20.103
            - name: prd1marketing04
              host: 10.80.20.104
            - name: prd1marketing05
              host: 10.80.20.105
            - name: prd1marketing06
              host: 10.80.20.106
            - name: prd1marketing07
              host: 10.80.20.107
            - name: prd1marketing08
              host: 10.80.20.108
            - name: prd1marketing09
              host: 10.80.20.109
            - name: prd1marketing10
              host: 10.80.20.110
            - name: prd1marketing11
              host: 10.80.20.111
            - name: prd1marketing12
              host: 10.80.20.112
