---

# Example of forcing pool members offline
#
# This example shows you how you can force a pool member offline
# by disabling its session and monitor states
#
# Requirements:
#
#   * Ansible >= 2.3
#

- name: Create pool members
  hosts: f5-test
  connection: local

  environment:
      F5_SERVER: "{{ inventory_hostname }}"
      F5_USER: "admin"
      F5_PASSWORD: "admin"
      F5_SERVER_PORT: "10443"
      F5_VALIDATE_CERTS: "no"

  vars:
      pool_name: "foo.pool"
      pool_lb_method: "round_robin"
      node_host: "10.10.10.10"
      node_port: 80
      node_description: "web server"
      connection_limit: 100
      rate_limit: 50
      ratio: 2

  tasks:
      - name: Create a pool
        bigip_pool:
            lb_method: "{{ pool_lb_method }}"
            name: "{{ pool_name }}"
            state: "present"

      - name: Add pool member
        bigip_pool_member:
            connection_limit: "{{ connection_limit }}"
            description: "{{ node_description }}"
            host: "{{ node_host }}"
            pool: "{{ pool_name }}"
            port: "{{ node_port }}"
            rate_limit: "{{ rate_limit }}"
            ratio: "{{ ratio }}"
            state: "present"

      - name: Force pool member offline
        bigip_pool_member:
            host: "{{ node_host }}"
            pool: "{{ pool_name }}"
            port: "{{ node_port }}"
            session_state: "disabled"
            monitor_state: "disabled"
            state: "present"
        register: result
