FROM python:3.6
MAINTAINER @caphrim007

# Directories used to hold command configs
RUN mkdir -p /root/.config/openstack && \
    mkdir -p /etc/jenkins_jobs && \
    mkdir -p /tmp/ansible.junit

# Misc symlinks
RUN ln -s /var/run/secrets/.gitconfig /root/.gitconfig

# Conveniance aliases
RUN echo 'alias ll="ls -l --color"' >> ~/.bashrc && \
    echo 'alias q="tail -f /tmp/q"' >> ~/.bashrc && \
    echo 'alias rq="rm -f /tmp/q"' >> ~/.bashrc && \
    echo 'export PATH=$PATH:/here/devtools/bin' >> ~/.bashrc && \
    echo 'eval "$(_F5ANSIBLE_COMPLETE=source /here/devtools/bin/f5ansible)"' >> ~/.bashrc

# Required package installation
RUN apt-get update && apt-get install -y \
    python-dev python-pip vim git-core wget curl \
    libffi-dev libssl-dev libxml2-dev libxslt1-dev \
    libjpeg62-turbo-dev zlib1g-dev python3-apt jq \
    sshpass rpm less

# Install required pip packages
RUN pip install --upgrade pip

# Because python gets installed in /usr/local/bin instead of /usr/bin
RUN ln -sf /usr/lib/python3/dist-packages/apt_pkg.cpython-34m-x86_64-linux-gnu.so /usr/local/lib/python3.6/apt_pkg.so && \
    ln -sf /usr/lib/python3/dist-packages/apt_inst.cpython-34m-x86_64-linux-gnu.so /usr/local/lib/python3.6/apt_inst.so && \
    ln -sf /usr/lib/python3/dist-packages/apt /usr/local/lib/python3.6/apt

# Install git-secrets
RUN git clone https://github.com/awslabs/git-secrets.git /tmp/git-secrets && \
    cd /tmp/git-secrets && \
    make install

# The dependencies of the f5-ansible repository are installed here.
#
# Note that the entire codebase is **NOT** installed because it is instead
# provided as a bind-mount when using docker-compose.
COPY requirements.test.txt /tmp/__src__/requirements.test.txt
RUN pip install -r /tmp/__src__/requirements.test.txt

# Clears any cache that may have been saved when running the package installation
# steps earlier.
RUN rm -rf /var/lib/apt/lists/*
RUN rm -rf /tmp/git-secrets

# The /here directory will be bind-mounted to your f5-ansible source tree,
# allowing you to use a proper editor outside of the container, and have the
# changes that editor makes reflected inside the container immediately.
WORKDIR /here
CMD ['/bin/bash']
